<?php

// config/crypto.php
return [

    // Definisikan timeframe yang akan dianalisis
    'timeframes' => [
        '1h' => ['label' => 'H1', 'limit' => 300],
        '4h' => ['label' => 'H4', 'limit' => 300],
        '1d' => ['label' => '1D', 'limit' => 300],
    ],

    // Parameter untuk indikator teknikal
    'indicators' => [
        'rsi_period' => 14,
        'macd_fast' => 12,
        'macd_slow' => 26,
        'macd_signal' => 9,
    ],

    // Pembobotan skor untuk setiap indikator
    'scoring_weights' => [
        'macd' => 2.0,
        'rsi' => 1.0,
        'volume' => 1.5,
    ],

    // Binance API Configuration (Legacy - now handled by providers)
    'binance_api' => [
        'base_url' => env('BINANCE_API_URL', 'https://api.binance.com'),
        'timeout' => env('BINANCE_API_TIMEOUT', 30),
    ],

    // Symbol filtering options
    'symbol_filters' => [
        'quote_assets' => ['USDT', 'BTC', 'ETH', 'BUSD'], // Only include these quote assets
        'exclude_symbols' => ['UP', 'DOWN', 'BULL', 'BEAR'], // Exclude leveraged tokens
        'min_volume_24h' => env('MIN_24H_VOLUME', 100000), // Minimum 24h volume in USD
        'max_symbols' => env('MAX_SYMBOLS', 500), // Limit number of symbols to fetch
    ],

    // Symbol format converter (BTC -> BTCUSDT)
    'symbol_converter' => [
        'BTC' => 'BTCUSDT',
        'ETH' => 'ETHUSDT',
        'BNB' => 'BNBUSDT',
        'ADA' => 'ADAUSDT',
        'XRP' => 'XRPUSDT',
        'SOL' => 'SOLUSDT',
        'DOT' => 'DOTUSDT',
        'DOGE' => 'DOGEUSDT',
        'AVAX' => 'AVAXUSDT',
        'LTC' => 'LTCUSDT',
        'LINK' => 'LINKUSDT',
        'MATIC' => 'MATICUSDT',
        'ALGO' => 'ALGOUSDT',
        'UNI' => 'UNIUSDT',
        'ATOM' => 'ATOMUSDT',
        'VET' => 'VETUSDT',
        'ICP' => 'ICPUSDT',
        'FIL' => 'FILUSDT',
        'TRX' => 'TRXUSDT',
        'ETC' => 'ETCUSDT',
        'XLM' => 'XLMUSDT',
        'THETA' => 'THETAUSDT',
        'EOS' => 'EOSUSDT',
        'AAVE' => 'AAVEUSDT',
        'COMP' => 'COMPUSDT',
        'SNX' => 'SNXUSDT',
        'YFI' => 'YFIUSDT',
        'SUSHI' => 'SUSHIUSDT',
        'CRV' => 'CRVUSDT',
        'MKR' => 'MKRUSDT',
        'ZRX' => 'ZRXUSDT',
        'BAT' => 'BATUSDT',
        'ZIL' => 'ZILUSDT',
        'ONT' => 'ONTUSDT',
        'QTUM' => 'QTUMUSDT',
        'ICX' => 'ICXUSDT',
        'LSK' => 'LSKUSDT',
        'WAVES' => 'WAVESUSDT',
        'BAND' => 'BANDUSDT',
        'OCEAN' => 'OCEANUSDT',
        'NMR' => 'NMRUSDT',
        'NEAR' => 'NEARUSDT',
        'FTT' => 'FTTUSDT',
        'ALICE' => 'ALICEUSDT',
        'CHZ' => 'CHZUSDT',
        'ENJ' => 'ENJUSDT',
        'MANA' => 'MANAUSDT',
        'SAND' => 'SANDUSDT',
        'GALA' => 'GALAUSDT',
        'APE' => 'APEUSDT',
        'LOOKS' => 'LOOKSUSDT',
        'IMX' => 'IMXUSDT',
        'FLOW' => 'FLOWUSDT',
        'AXS' => 'AXSUSDT',
        'DYDX' => 'DYDXUSDT',
        'GRT' => 'GRTUSDT',
        'LPT' => 'LPTUSDT',
        'API3' => 'API3USDT',
        'TLM' => 'TLMUSDT',
        'PEOPLE' => 'PEOPLEUSDT',
        'ROSE' => 'ROSEUSDT',
        'SKL' => 'SKLUSDT',
        'CELO' => 'CELOUSDT',
        'KLAY' => 'KLAYUSDT',
        'SXP' => 'SXPUSDT',
        'RUNE' => 'RUNEUSDT',
        'LINA' => 'LINAUSDT',
        'MTL' => 'MTLUSDT',
        'ZEC' => 'ZECUSDT',
        'DASH' => 'DASHUSDT',
        'SC' => 'SCUSDT',
        'CHR' => 'CHRUSDT',
        'XEM' => 'XEMUSDT',
        'STORJ' => 'STORJUSDT',
        'BLZ' => 'BLZUSDT',
        'IRIS' => 'IRISUSDT',
        'COTI' => 'COTIUSDT',
        'STPT' => 'STPTUSDT',
        'DATA' => 'DATAUSDT',
        'KEY' => 'KEYUSDT',
        'DOCK' => 'DOCKUSDT',
        'WAN' => 'WANUSDT',
        'FUN' => 'FUNUSDT',
        'CVC' => 'CVCUSDT',
        'VIA' => 'VIAUSDT',
        'BEAM' => 'BEAMUSDT',
        'ARDR' => 'ARDRUSDT',
        'DGB' => 'DGBUSDT',
        'STEEM' => 'STEEMUSDT',
        'ARK' => 'ARKUSDT',
        'GRS' => 'GRSUSDT',
        'VTC' => 'VTCUSDT',
        'GAME' => 'GAMEUSDT',
        'DCR' => 'DCRUSDT',
        'PIVX' => 'PIVXUSDT',
        'XWC' => 'XWCUSDT',
        'NXT' => 'NXTUSDT',
        'BURG' => 'BURGUSDT',
        'GBYTE' => 'GBYTEUSDT',
        'NLG' => 'NLGUSDT',
        'RBY' => 'RBYUSDT',
        'POT' => 'POTUSDT',
        'BLK' => 'BLKUSDT',
        'EMC2' => 'EMC2USDT',
        'RIC' => 'RICUSDT',
        'FLO' => 'FLOUSDT',
        'MAID' => 'MAIDUSDT',
        'EXP' => 'EXPUSDT',
        'GRC' => 'GRCUSDT',
        'CLAM' => 'CLAMUSDT',
        'NVC' => 'NVCUSDT',
        'CURE' => 'CUREUSDT',
        'START' => 'STARTUSDT',
        'XDN' => 'XDNUSDT',
        'XST' => 'XSTUSDT',
        'BITB' => 'BITBUSDT',
        'SIB' => 'SIBUSDT',
        'SYSC' => 'SYSCUSDT',
        'NEOS' => 'NEOSUSDT',
        'XCP' => 'XCPUSDT',
        'MONA' => 'MONAUSDT',
        'CLUB' => 'CLUBUSDT',
        'VRC' => 'VRCUSDT',
        'TIPS' => 'TIPSUSDT',
        'HIFUN' => 'HIFUNUSDT',
        'ADC' => 'ADCUSDT',
        'SLG' => 'SLGUSDT',
        'CORG' => 'CORGUSDT',
        'AIB' => 'AIBUSDT',
        'GEO' => 'GEOUSDT',
        'FLDC' => 'FLDCUSDT',
        'HYP' => 'HYPUSDT',
        'HYPE' => 'HYPE',  // Add HYPE to converter
        'ASTER' => 'ASTERUSDT',
        'XPL' => 'XPLUSDT',
        'GO' => 'GOUSDT',
        'ERC' => 'ERCUSDT',
        'VDO' => 'VDOUSDT',
        'SXC' => 'SXCUSDT',
        'LKY' => 'LKYUSDT',
        'CPC' => 'CPCUSDT',
        'NOTE' => 'NOTEUSDT',
        'EMD' => 'EMDUSDT',
        'LYNX' => 'LYNXUSDT',
        'DBIX' => 'DBIXUSDT',
        'MEME' => 'MEMEUSDT',
        'CS' => 'CSUSDT',
        'PHS' => 'PHSUSDT',
        'NET' => 'NETUSDT',
        'BOS' => 'BOSUSDT',
        'QWARK' => 'QWARKUSDT',
        'TER' => 'TERUSDT',
        'SWING' => 'SWINGUSDT',
        'SAK' => 'SAKUSDT',
        '32BIT' => '32BITUSDT',
        'COVAL' => 'COVALUSDT',
        'EDG' => 'EDGUSDT',
        'HEAT' => 'HEATUSDT',
        'CLOAK' => 'CLOAKUSDT',
        'XEL' => 'XELUSDT',
        'AMP' => 'AMPUSDT',
        'DMD' => 'DMDUSDT',
        'GAM' => 'GAMUSDT',
        'SPHR' => 'SPHRUSDT',
        'NXS' => 'NXSUSDT',
    ],

    // API Provider Configuration
    'api_providers' => [
        'default' => env('DEFAULT_API_PROVIDER', 'coingecko'),
        'fallback_enabled' => env('API_FALLBACK_ENABLED', true),
        'rate_limit_cache_duration' => env('API_RATE_LIMIT_CACHE', 300), // 5 minutes
        'providers' => [
            'binance' => [
                'name' => 'Binance API',
                'priority' => 1, // Second priority
                'enabled' => env('BINANCE_API_ENABLED', true),
                'base_url' => env('BINANCE_API_URL', 'https://api.binance.com'),
                'timeout' => env('BINANCE_API_TIMEOUT', 30),
                'retry_attempts' => env('BINANCE_API_RETRY', 3),
                'retry_delay' => env('BINANCE_API_RETRY_DELAY', 1000),
                'rate_limits' => [
                    'requests_per_minute' => env('BINANCE_RATE_LIMIT', 1200),
                    'requests_per_second' => env('BINANCE_RATE_LIMIT_SECOND', 10),
                ],
            ],
            'coingecko' => [
                'name' => 'CoinGecko API',
                'priority' => 0, // Highest priority (default)
                'enabled' => env('COINGECKO_API_ENABLED', true),
                'base_url' => env('COINGECKO_API_URL', 'https://api.coingecko.com/api/v3/'),
                'api_key' => env('COINGECKO_API_KEY', ''), // Optional for free tier
                'timeout' => env('COINGECKO_API_TIMEOUT', 30),
                'retry_attempts' => env('COINGECKO_API_RETRY', 3),
                'retry_delay' => env('COINGECKO_API_RETRY_DELAY', 2000),
                'rate_limits' => [
                    'requests_per_minute' => env('COINGECKO_RATE_LIMIT', 50),
                    'requests_per_second' => env('COINGECKO_RATE_LIMIT_SECOND', 2),
                ],
            ],
        ],
        'coinlore' => [
            'max_klines_limit' => 1000,
            'supported_intervals' => ['5m', '15m', '30m', '1h', '4h', '1d'],
            'requires_uppercase' => false,
            'supported_quote_assets' => ['usd'],
            'coin_id_mapping' => [
                'BTCUSDT' => '90',
                'ETHUSDT' => '80',
                'BNBUSDT' => '2710',
                'ADAUSDT' => '257',
                'XRPUSDT' => '58',
                'SOLUSDT' => '48543',
                'DOTUSDT' => '11815',
                'DOGEUSDT' => '2',
                'AVAXUSDT' => '23210',
                'LTCUSDT' => '1',
            ],
        ],
    ],

    // Coin-to-API Mapping Configuration
    'coin_api_mapping' => [
        // Load symbol mappings from external file
        'symbol_mappings' => include_once __DIR__ . '/crypto_symbol_mapping.php',

        // Primary API for each coin (first priority) - now Coinpaprika is default
        'primary_api' => [
            // Coinpaprika USDT pairs (now the default)
            'BTC' => 'coinpaprika',
            'ETH' => 'coinpaprika',
            'BNB' => 'coinpaprika',
            'ADA' => 'coinpaprika',
            'XRP' => 'coinpaprika',
            'SOL' => 'coinpaprika',
            'DOT' => 'coinpaprika',
            'DOGE' => 'coinpaprika',
            'AVAX' => 'coinpaprika',
            'LTC' => 'coinpaprika',
            'LINK' => 'coinpaprika',
            'MATIC' => 'coinpaprika',
            'ALGO' => 'coinpaprika',
            'UNI' => 'coinpaprika',
            'ATOM' => 'coinpaprika',
            'VET' => 'coinpaprika',
            'ICP' => 'coinpaprika',
            'FIL' => 'coinpaprika',
            'TRX' => 'coinpaprika',
            'ETC' => 'coinpaprika',
            'XLM' => 'coincappro',
            'THETA' => 'coincappro',
            'EOS' => 'coincappro',
            'AAVE' => 'coincappro',
            'COMP' => 'coincappro',
            'SNX' => 'coincappro',
            'YFI' => 'coincappro',
            'SUSHI' => 'coincappro',
            'CRV' => 'coincappro',
            'MKR' => 'coincappro',
            'UMA' => 'coincappro',
            'ZRX' => 'coincappro',
            'BAT' => 'coincappro',
            'ZIL' => 'coincappro',
            'ONT' => 'coincappro',
            'QTUM' => 'coincappro',
            'ICX' => 'coincappro',
            'LSK' => 'coincappro',
            'WAVES' => 'coincappro',
            'BAND' => 'coincappro',
            'OCEAN' => 'coincappro',
            'NMR' => 'coincappro',
            'NEAR' => 'coincappro',
            'FTT' => 'coincappro',
            'ALICE' => 'coincappro',
            'CHZ' => 'coincappro',
            'ENJ' => 'coincappro',
            'MANA' => 'coincappro',
            'SAND' => 'coincappro',
            'GALA' => 'coincappro',
            'APE' => 'coincappro',
            'LOOKS' => 'coincappro',
            'IMX' => 'coincappro',
            'FLOW' => 'coincappro',
            'AXS' => 'coincappro',
            'DYDX' => 'coincappro',
            'GRT' => 'coincappro',
            'LPT' => 'coincappro',
            'API3' => 'coincappro',
            'TLM' => 'coincappro',
            'PEOPLE' => 'coincappro',
            'ROSE' => 'coincappro',
            'SKL' => 'coincappro',
            'CELO' => 'coincappro',
            'KLAY' => 'coincappro',
            'SXP' => 'coincappro',
            'RUNE' => 'coincappro',
            'LINA' => 'coincappro',
            'MTL' => 'coincappro',
            'ZEC' => 'coincappro',
            'DASH' => 'coincappro',
            'SC' => 'freecryptoapi',
            'CHR' => 'freecryptoapi',
            'XEM' => 'freecryptoapi',
            'STORJ' => 'freecryptoapi',
            'BLZ' => 'freecryptoapi',
            'IRIS' => 'freecryptoapi',
            'COTI' => 'freecryptoapi',
            'STPT' => 'freecryptoapi',
            'DATA' => 'freecryptoapi',
            'KEY' => 'freecryptoapi',
            'DOCK' => 'freecryptoapi',
            'WAN' => 'freecryptoapi',
            'FUN' => 'freecryptoapi',
            'CVC' => 'freecryptoapi',
            'VIA' => 'freecryptoapi',
            'BEAM' => 'freecryptoapi',
            'ARDR' => 'freecryptoapi',
            'DGB' => 'freecryptoapi',
            'STEEM' => 'freecryptoapi',
            'STRATIS' => 'freecryptoapi',
            'ARK' => 'freecryptoapi',
            'GRS' => 'freecryptoapi',
            'VTC' => 'freecryptoapi',
            'GAME' => 'freecryptoapi',
            'DCR' => 'freecryptoapi',
            'PIVX' => 'freecryptoapi',
            'XWC' => 'freecryptoapi',
            'NXT' => 'freecryptoapi',
            'BURG' => 'freecryptoapi',
            'GBYTE' => 'freecryptoapi',
            'NLG' => 'freecryptoapi',
            'RBY' => 'freecryptoapi',
            'POT' => 'freecryptoapi',
            'BLK' => 'freecryptoapi',
            'EMC2' => 'freecryptoapi',
            'RIC' => 'freecryptoapi',
            'FLO' => 'freecryptoapi',
            'MAID' => 'freecryptoapi',
            'EXP' => 'freecryptoapi',
            'GRC' => 'freecryptoapi',
            'CLAM' => 'freecryptoapi',
            'NVC' => 'freecryptoapi',
            'CURE' => 'freecryptoapi',
            'START' => 'freecryptoapi',
            'XDN' => 'freecryptoapi',
            'XST' => 'freecryptoapi',
            'BITB' => 'freecryptoapi',
            'SIB' => 'freecryptoapi',
            'SYSC' => 'freecryptoapi',
            'NEOS' => 'freecryptoapi',
            'XCP' => 'freecryptoapi',
            'MONA' => 'freecryptoapi',
            'CLUB' => 'freecryptoapi',
            'VRC' => 'freecryptoapi',
            'TIPS' => 'freecryptoapi',
            'HIFUN' => 'freecryptoapi',
            'ADC' => 'freecryptoapi',
            'SLG' => 'freecryptoapi',
            'CORG' => 'freecryptoapi',
            'AIB' => 'freecryptoapi',
            'GEO' => 'freecryptoapi',
            'FLDC' => 'freecryptoapi',
            'HYP' => 'freecryptoapi',
            'HYPE' => 'coincappro',  // Add HYPE to primary API
            'ASTER' => 'coincappro',
            'XPL' => 'coincappro',
            'GO' => 'coincappro',
            'ERC' => 'coincappro',
            'VDO' => 'coincappro',
            'SXC' => 'coincappro',
            'LKY' => 'coincappro',
            'CPC' => 'coincappro',
            'NOTE' => 'coincappro',
            'EMD' => 'coincappro',
            'LYNX' => 'coincappro',
            'DBIX' => 'coincappro',
            'MEME' => 'coincappro',
            'CS' => 'coincappro',
            'PHS' => 'coincappro',
            'NET' => 'coincappro',
            'BOS' => 'coincappro',
            'QWARK' => 'coincappro',
            'TER' => 'coincappro',
            'SWING' => 'coincappro',
            'SAK' => 'coincappro',
            '32BIT' => 'coincappro',
            'COVAL' => 'coincappro',
            'EDG' => 'coincappro',
            'HEAT' => 'coincappro',
            'CLOAK' => 'coincappro',
            'XEL' => 'coincappro',
            'AMP' => 'coincappro',
            'DMD' => 'coincappro',
            'GAM' => 'coincappro',
            'SPHR' => 'coincappro',
            'NXS' => 'coincappro',
            // CoinPaprika as fallback for all coins
            'BTC' => 'coinpaprika',
            'ETH' => 'coinpaprika',
            'BNB' => 'coinpaprika',
            'ADA' => 'coinpaprika',
            'XRP' => 'coinpaprika',
            'SOL' => 'coinpaprika',
            'DOT' => 'coinpaprika',
            'DOGE' => 'coinpaprika',
            'AVAX' => 'coinpaprika',
            'LTC' => 'coinpaprika',
            'LINK' => 'coinpaprika',
            'MATIC' => 'coinpaprika',
            'ALGO' => 'coinpaprika',
            'UNI' => 'coinpaprika',
            'ATOM' => 'coinpaprika',
            'VET' => 'coinpaprika',
            'ICP' => 'coinpaprika',
            'FIL' => 'coinpaprika',
            'TRX' => 'coinpaprika',
            'ETC' => 'coinpaprika',
        ],

        // Fallback APIs for coins (if primary fails) - reordered to put CoinCap Pro first
        'fallback_apis' => [
            'BTC' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinlore', 'coinpaprika', 'coindesk'],
            'ETH' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinlore', 'coinpaprika'],
            'BNB' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'ADA' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'XRP' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'SOL' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'DOT' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'DOGE' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'AVAX' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'LTC' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'LINK' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'MATIC' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'ALGO' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'UNI' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'ATOM' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'VET' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'ICP' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'FIL' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'TRX' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
            'ETC' => ['coincappro', 'freecryptoapi', 'binance', 'coingecko', 'coinpaprika'],
        ],

        // API-specific coin limitations
        'api_limitations' => [
            'binance' => [
                'max_klines_limit' => 1000,
                'supported_intervals' => ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M'],
                'requires_uppercase' => true,
                'supported_quote_assets' => ['USDT', 'BTC', 'ETH', 'BUSD'],
            ],
            'coingecko' => [
                'max_klines_limit' => 365,
                'supported_intervals' => ['1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'coin_id_mapping' => [
                    'BTCUSDT' => 'bitcoin',
                    'ETHUSDT' => 'ethereum',
                    'BNBUSDT' => 'binancecoin',
                    'ADAUSDT' => 'cardano',
                    'XRPUSDT' => 'ripple',
                    'SOLUSDT' => 'solana',
                    'DOTUSDT' => 'polkadot',
                    'DOGEUSDT' => 'dogecoin',
                    'AVAXUSDT' => 'avalanche-2',
                    'LTCUSDT' => 'litecoin',
                    'LINKUSDT' => 'chainlink',
                    'MATICUSDT' => 'matic-network',
                    'ALGOUSDT' => 'algorand',
                    'UNIUSDT' => 'uniswap',
                    'ATOMUSDT' => 'cosmos',
                    'VETUSDT' => 'vechain',
                    'ICPUSDT' => 'internet-computer',
                    'FILUSDT' => 'filecoin',
                    'TRXUSDT' => 'tron',
                    'ETCUSDT' => 'ethereum-classic',
                ],
            ],
            'freecryptoapi' => [
                'max_klines_limit' => 500,
                'supported_intervals' => ['1m', '5m', '15m', '30m', '1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'symbol_format' => 'BTC-USDT', // Different format
                'coin_id_mapping' => [
                    'BTCUSDT' => 'BTC-USDT',
                    'ETHUSDT' => 'ETH-USDT',
                    'BNBUSDT' => 'BNB-USDT',
                    'ADAUSDT' => 'ADA-USDT',
                    'XRPUSDT' => 'XRP-USDT',
                    'SOLUSDT' => 'SOL-USDT',
                    'DOTUSDT' => 'DOT-USDT',
                    'DOGEUSDT' => 'DOGE-USDT',
                    'AVAXUSDT' => 'AVAX-USDT',
                    'LTCUSDT' => 'LTC-USDT',
                    'LINKUSDT' => 'LINK-USDT',
                    'MATICUSDT' => 'MATIC-USDT',
                    'ALGOUSDT' => 'ALGO-USDT',
                    'UNIUSDT' => 'UNI-USDT',
                    'ATOMUSDT' => 'ATOM-USDT',
                    'VETUSDT' => 'VET-USDT',
                    'ICPUSDT' => 'ICP-USDT',
                    'FILUSDT' => 'FIL-USDT',
                    'TRXUSDT' => 'TRX-USDT',
                    'ETCUSDT' => 'ETC-USDT',
                ],
            ],
            'coincappro' => [
                'max_klines_limit' => 1000,
                'supported_intervals' => ['1m', '5m', '15m', '30m', '1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'coin_id_mapping' => [
                    'BTCUSDT' => 'bitcoin',
                    'ETHUSDT' => 'ethereum',
                    'BNBUSDT' => 'binance-coin',
                    'ADAUSDT' => 'cardano',
                    'XRPUSDT' => 'xrp',
                    'SOLUSDT' => 'solana',
                    'DOTUSDT' => 'polkadot',
                    'DOGEUSDT' => 'dogecoin',
                    'AVAXUSDT' => 'avalanche',
                    'LTCUSDT' => 'litecoin',
                    'LINKUSDT' => 'chainlink',
                    'MATICUSDT' => 'polygon',
                    'ALGOUSDT' => 'algorand',
                    'UNIUSDT' => 'uniswap',
                    'ATOMUSDT' => 'cosmos',
                    'VETUSDT' => 'vechain',
                    'ICPUSDT' => 'internet-computer',
                    'FILUSDT' => 'filecoin',
                    'TRXUSDT' => 'tron',
                    'ETCUSDT' => 'ethereum-classic',
                ],
            ],
            'coinpaprika' => [
                'max_klines_limit' => 200, // Increased limit to support analysis requirements
                'supported_intervals' => ['1h', '1d'], // Limited intervals for free tier
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'note' => 'Free tier only supports current price data. Historical data requires paid plan.',
                'coin_id_mapping' => [
                    'BTCUSDT' => 'btc-bitcoin',
                    'ETHUSDT' => 'eth-ethereum',
                    'BNBUSDT' => 'bnb-binance-coin',
                    'ADAUSDT' => 'ada-cardano',
                    'XRPUSDT' => 'xrp-xrp',
                    'SOLUSDT' => 'sol-solana',
                    'DOTUSDT' => 'dot-polkadot',
                    'DOGEUSDT' => 'doge-dogecoin',
                    'AVAXUSDT' => 'avax-avalanche',
                    'LTCUSDT' => 'ltc-litecoin',
                    'LINKUSDT' => 'link-chainlink',
                    'MATICUSDT' => 'matic-polygon',
                    'ALGOUSDT' => 'algo-algorand',
                    'UNIUSDT' => 'uni-uniswap',
                    'ATOMUSDT' => 'atom-cosmos',
                    'VETUSDT' => 'vet-vechain',
                    'ICPUSDT' => 'icp-internet-computer',
                    'FILUSDT' => 'fil-filecoin',
                    'TRXUSDT' => 'trx-tron',
                    'ETCUSDT' => 'etc-ethereum-classic',
                ],
            ],
            'coindesk' => [
                'max_klines_limit' => 365, // 1 year of historical data
                'supported_intervals' => ['1h', '4h', '1d'], // Supports multiple intervals
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'note' => 'Primarily Bitcoin-focused API with historical data support.',
                'coin_id_mapping' => [
                    'BTCUSDT' => 'BTC',
                    'BTC' => 'BTC',
                ],
            ],
        ],
    ],
];