<?php

// config/crypto.php
return [

    // Definisikan timeframe yang akan dianalisis
    'timeframes' => [
        '1h' => ['label' => 'H1', 'limit' => 300],
        '4h' => ['label' => 'H4', 'limit' => 300],
        '1d' => ['label' => '1D', 'limit' => 300],
    ],

    // Parameter untuk indikator teknikal
    'indicators' => [
        'rsi_period' => 14,
        'macd_fast' => 12,
        'macd_slow' => 26,
        'macd_signal' => 9,
    ],

    // Pembobotan skor untuk setiap indikator
    'scoring_weights' => [
        'macd' => 2.0,
        'rsi' => 1.0,
        'volume' => 1.5,
    ],

    // Binance API Configuration (Legacy - now handled by providers)
    'binance_api' => [
        'base_url' => env('BINANCE_API_URL', 'https://api.binance.com'),
        'timeout' => env('BINANCE_API_TIMEOUT', 30),
    ],

    // Symbol filtering options
    'symbol_filters' => [
        'quote_assets' => ['USDT', 'BTC', 'ETH', 'BUSD'], // Only include these quote assets
        'exclude_symbols' => ['UP', 'DOWN', 'BULL', 'BEAR'], // Exclude leveraged tokens
        'min_volume_24h' => env('MIN_24H_VOLUME', 100000), // Minimum 24h volume in USD
        'max_symbols' => env('MAX_SYMBOLS', 500), // Limit number of symbols to fetch
    ],

    // Symbol format converter (BTC -> BTCUSDT)
    'symbol_converter' => [
        'BTC' => 'BTCUSDT',
        'ETH' => 'ETHUSDT',
        'BNB' => 'BNBUSDT',
        'ADA' => 'ADAUSDT',
        'XRP' => 'XRPUSDT',
        'SOL' => 'SOLUSDT',
        'DOT' => 'DOTUSDT',
        'DOGE' => 'DOGEUSDT',
        'AVAX' => 'AVAXUSDT',
        'LTC' => 'LTCUSDT',
        'LINK' => 'LINKUSDT',
        'MATIC' => 'MATICUSDT',
        'ALGO' => 'ALGOUSDT',
        'UNI' => 'UNIUSDT',
        'ATOM' => 'ATOMUSDT',
        'VET' => 'VETUSDT',
        'ICP' => 'ICPUSDT',
        'FIL' => 'FILUSDT',
        'TRX' => 'TRXUSDT',
        'ETC' => 'ETCUSDT',
        'XLM' => 'XLMUSDT',
        'THETA' => 'THETAUSDT',
        'EOS' => 'EOSUSDT',
        'AAVE' => 'AAVEUSDT',
        'COMP' => 'COMPUSDT',
        'SNX' => 'SNXUSDT',
        'YFI' => 'YFIUSDT',
        'SUSHI' => 'SUSHIUSDT',
        'CRV' => 'CRVUSDT',
        'MKR' => 'MKRUSDT',
        'ZRX' => 'ZRXUSDT',
        'BAT' => 'BATUSDT',
        'ZIL' => 'ZILUSDT',
        'ONT' => 'ONTUSDT',
        'QTUM' => 'QTUMUSDT',
        'ICX' => 'ICXUSDT',
        'LSK' => 'LSKUSDT',
        'WAVES' => 'WAVESUSDT',
        'BAND' => 'BANDUSDT',
        'OCEAN' => 'OCEANUSDT',
        'NMR' => 'NMRUSDT',
        'NEAR' => 'NEARUSDT',
        'FTT' => 'FTTUSDT',
        'ALICE' => 'ALICEUSDT',
        'CHZ' => 'CHZUSDT',
        'ENJ' => 'ENJUSDT',
        'MANA' => 'MANAUSDT',
        'SAND' => 'SANDUSDT',
        'GALA' => 'GALAUSDT',
        'APE' => 'APEUSDT',
        'LOOKS' => 'LOOKSUSDT',
        'IMX' => 'IMXUSDT',
        'FLOW' => 'FLOWUSDT',
        'AXS' => 'AXSUSDT',
        'DYDX' => 'DYDXUSDT',
        'GRT' => 'GRTUSDT',
        'LPT' => 'LPTUSDT',
        'API3' => 'API3USDT',
        'TLM' => 'TLMUSDT',
        'PEOPLE' => 'PEOPLEUSDT',
        'ROSE' => 'ROSEUSDT',
        'SKL' => 'SKLUSDT',
        'CELO' => 'CELOUSDT',
        'KLAY' => 'KLAYUSDT',
        'SXP' => 'SXPUSDT',
        'RUNE' => 'RUNEUSDT',
        'LINA' => 'LINAUSDT',
        'MTL' => 'MTLUSDT',
        'ZEC' => 'ZECUSDT',
        'DASH' => 'DASHUSDT',
        'SC' => 'SCUSDT',
        'CHR' => 'CHRUSDT',
        'XEM' => 'XEMUSDT',
        'STORJ' => 'STORJUSDT',
        'BLZ' => 'BLZUSDT',
        'IRIS' => 'IRISUSDT',
        'COTI' => 'COTIUSDT',
        'STPT' => 'STPTUSDT',
        'DATA' => 'DATAUSDT',
        'KEY' => 'KEYUSDT',
        'DOCK' => 'DOCKUSDT',
        'WAN' => 'WANUSDT',
        'FUN' => 'FUNUSDT',
        'CVC' => 'CVCUSDT',
        'VIA' => 'VIAUSDT',
        'BEAM' => 'BEAMUSDT',
        'ARDR' => 'ARDRUSDT',
        'DGB' => 'DGBUSDT',
        'STEEM' => 'STEEMUSDT',
        'ARK' => 'ARKUSDT',
        'GRS' => 'GRSUSDT',
        'VTC' => 'VTCUSDT',
        'GAME' => 'GAMEUSDT',
        'DCR' => 'DCRUSDT',
        'PIVX' => 'PIVXUSDT',
        'XWC' => 'XWCUSDT',
        'NXT' => 'NXTUSDT',
        'BURG' => 'BURGUSDT',
        'GBYTE' => 'GBYTEUSDT',
        'NLG' => 'NLGUSDT',
        'RBY' => 'RBYUSDT',
        'POT' => 'POTUSDT',
        'BLK' => 'BLKUSDT',
        'EMC2' => 'EMC2USDT',
        'RIC' => 'RICUSDT',
        'FLO' => 'FLOUSDT',
        'MAID' => 'MAIDUSDT',
        'EXP' => 'EXPUSDT',
        'GRC' => 'GRCUSDT',
        'CLAM' => 'CLAMUSDT',
        'NVC' => 'NVCUSDT',
        'CURE' => 'CUREUSDT',
        'START' => 'STARTUSDT',
        'XDN' => 'XDNUSDT',
        'XST' => 'XSTUSDT',
        'BITB' => 'BITBUSDT',
        'SIB' => 'SIBUSDT',
        'SYSC' => 'SYSCUSDT',
        'NEOS' => 'NEOSUSDT',
        'XCP' => 'XCPUSDT',
        'MONA' => 'MONAUSDT',
        'CLUB' => 'CLUBUSDT',
        'VRC' => 'VRCUSDT',
        'TIPS' => 'TIPSUSDT',
        'HIFUN' => 'HIFUNUSDT',
        'ADC' => 'ADCUSDT',
        'SLG' => 'SLGUSDT',
        'CORG' => 'CORGUSDT',
        'AIB' => 'AIBUSDT',
        'GEO' => 'GEOUSDT',
        'FLDC' => 'FLDCUSDT',
        'HYP' => 'HYPUSDT',
        'HYPE' => 'HYPEUSDT',
        'ASTER' => 'ASTERUSDT',
        'XPL' => 'XPLUSDT',
        'GO' => 'GOUSDT',
        'ERC' => 'ERCUSDT',
        'VDO' => 'VDOUSDT',
        'SXC' => 'SXCUSDT',
        'LKY' => 'LKYUSDT',
        'CPC' => 'CPCUSDT',
        'NOTE' => 'NOTEUSDT',
        'EMD' => 'EMDUSDT',
        'LYNX' => 'LYNXUSDT',
        'DBIX' => 'DBIXUSDT',
        'MEME' => 'MEMEUSDT',
        'CS' => 'CSUSDT',
        'PHS' => 'PHSUSDT',
        'NET' => 'NETUSDT',
        'BOS' => 'BOSUSDT',
        'QWARK' => 'QWARKUSDT',
        'TER' => 'TERUSDT',
        'SWING' => 'SWINGUSDT',
        'SAK' => 'SAKUSDT',
        '32BIT' => '32BITUSDT',
        'COVAL' => 'COVALUSDT',
        'EDG' => 'EDGUSDT',
        'HEAT' => 'HEATUSDT',
        'CLOAK' => 'CLOAKUSDT',
        'XEL' => 'XELUSDT',
        'AMP' => 'AMPUSDT',
        'DMD' => 'DMDUSDT',
        'GAM' => 'GAMUSDT',
        'SPHR' => 'SPHRUSDT',
        'NXS' => 'NXSUSDT',
    ],

    // API Provider Configuration
    'api_providers' => [
        'default' => env('DEFAULT_API_PROVIDER', 'coingecko'),
        'fallback_enabled' => env('API_FALLBACK_ENABLED', true),
        'rate_limit_cache_duration' => env('API_RATE_LIMIT_CACHE', 300), // 5 minutes
        'providers' => [
            'binance' => [
                'name' => 'Binance API',
                'priority' => 0, // Highest priority
                'enabled' => env('BINANCE_API_ENABLED', true),
                'base_url' => env('BINANCE_API_URL', 'https://api.binance.com'),
                'timeout' => env('BINANCE_API_TIMEOUT', 30),
                'retry_attempts' => env('BINANCE_API_RETRY', 3),
                'retry_delay' => env('BINANCE_API_RETRY_DELAY', 1000),
                'rate_limits' => [
                    'requests_per_minute' => env('BINANCE_RATE_LIMIT', 1200),
                    'requests_per_second' => env('BINANCE_RATE_LIMIT_SECOND', 10),
                ],
            ],
            'coingecko' => [
                'name' => 'CoinGecko API',
                'priority' => 1, // Second priority
                'enabled' => env('COINGECKO_API_ENABLED', true),
                'base_url' => env('COINGECKO_API_URL', 'https://api.coingecko.com/api/v3'),
                'api_key' => env('COINGECKO_API_KEY', ''),
                'timeout' => env('COINGECKO_API_TIMEOUT', 30),
                'retry_attempts' => env('COINGECKO_API_RETRY', 3),
                'retry_delay' => env('COINGECKO_API_RETRY_DELAY', 2000),
                'rate_limits' => [
                    'requests_per_minute' => env('COINGECKO_RATE_LIMIT', 50),
                    'requests_per_second' => env('COINGECKO_RATE_LIMIT_SECOND', 2),
                ],
            ],
            'freecryptoapi' => [
                'name' => 'Free Crypto API',
                'priority' => 2, // Third priority (fallback)
                'enabled' => env('FREECRYPTOAPI_ENABLED', true),
                'base_url' => env('FREECRYPTOAPI_URL', 'https://freecryptoapi.com/api/v1'),
                'api_key' => env('FREECRYPTOAPI_KEY', 'xccc177q0n8g9cf3t43n'),
                'timeout' => env('FREECRYPTOAPI_TIMEOUT', 30),
                'retry_attempts' => env('FREECRYPTOAPI_RETRY', 3),
                'retry_delay' => env('FREECRYPTOAPI_RETRY_DELAY', 3000),
                'rate_limits' => [
                    'requests_per_minute' => env('FREECRYPTOAPI_RATE_LIMIT', 100),
                    'requests_per_second' => env('FREECRYPTOAPI_RATE_LIMIT_SECOND', 2),
                ],
            ],
            'coincappro' => [
                'name' => 'CoinCap Pro API',
                'priority' => 0, // High priority (requires API key)
                'enabled' => env('COINCAPPRO_API_ENABLED', true),
                'base_url' => env('COINCAPPRO_API_URL', 'https://pro-api.coincap.io/v2'),
                'api_key' => env('COINCAPPRO_API_KEY', ''), // Requires API key
                'timeout' => env('COINCAPPRO_API_TIMEOUT', 30),
                'retry_attempts' => env('COINCAPPRO_API_RETRY', 3),
                'retry_delay' => env('COINCAPPRO_API_RETRY_DELAY', 2000),
                'rate_limits' => [
                    'requests_per_minute' => env('COINCAPPRO_RATE_LIMIT', 1000),
                    'requests_per_second' => env('COINCAPPRO_RATE_LIMIT_SECOND', 5),
                ],
            ],
            'coinlore' => [
                'name' => 'CoinLore API',
                'priority' => 3, // Fourth priority (fallback)
                'enabled' => env('COINLORE_API_ENABLED', true),
                'base_url' => env('COINLORE_API_URL', 'https://api.coinlore.net/api'),
                'api_key' => env('COINLORE_API_KEY', ''), // Optional API key
                'timeout' => env('COINLORE_API_TIMEOUT', 30),
                'retry_attempts' => env('COINLORE_API_RETRY', 3),
                'retry_delay' => env('COINLORE_API_RETRY_DELAY', 3000),
                'rate_limits' => [
                    'requests_per_minute' => env('COINLORE_RATE_LIMIT', 100),
                    'requests_per_second' => env('COINLORE_RATE_LIMIT_SECOND', 2),
                ],
            ],
        ],
        'coinlore' => [
            'max_klines_limit' => 1000,
            'supported_intervals' => ['5m', '15m', '30m', '1h', '4h', '1d'],
            'requires_uppercase' => false,
            'supported_quote_assets' => ['usd'],
            'coin_id_mapping' => [
                'BTCUSDT' => '90',
                'ETHUSDT' => '80',
                'BNBUSDT' => '2710',
                'ADAUSDT' => '257',
                'XRPUSDT' => '58',
                'SOLUSDT' => '48543',
                'DOTUSDT' => '11815',
                'DOGEUSDT' => '2',
                'AVAXUSDT' => '23210',
                'LTCUSDT' => '1',
            ],
        ],
    ],

    // Coin-to-API Mapping Configuration
    'coin_api_mapping' => [
        // Primary API for each coin (first priority)
        'primary_api' => [
            // Binance USDT pairs (most comprehensive)
            'BTCUSDT' => 'binance',
            'ETHUSDT' => 'binance',
            'BNBUSDT' => 'binance',
            'ADAUSDT' => 'binance',
            'XRPUSDT' => 'binance',
            'SOLUSDT' => 'binance',
            'DOTUSDT' => 'binance',
            'DOGEUSDT' => 'binance',
            'AVAXUSDT' => 'binance',
            'LTCUSDT' => 'binance',
            'LINKUSDT' => 'binance',
            'MATICUSDT' => 'binance',
            'ALGOUSDT' => 'binance',
            'UNIUSDT' => 'binance',
            'ATOMUSDT' => 'binance',
            'VETUSDT' => 'binance',
            'ICPUSDT' => 'binance',
            'FILUSDT' => 'binance',
            'TRXUSDT' => 'binance',
            'ETCUSDT' => 'binance',
            'XLMUSDT' => 'binance',
            'THETAUSDT' => 'binance',
            'EOSUSDT' => 'binance',
            'AAVEUSDT' => 'binance',
            'COMPUSDT' => 'binance',
            'SNXUSDT' => 'binance',
            'YFIUSDT' => 'binance',
            'SUSHIUSDT' => 'binance',
            'CRVUSDT' => 'binance',
            'MKRUSDT' => 'binance',
            'UMAUSDT' => 'binance',
            'ZRXUSDT' => 'binance',
            'BATUSDT' => 'binance',
            'ZILUSDT' => 'binance',
            'ONTUSDT' => 'binance',
            'QTUMUSDT' => 'binance',
            'ICXUSDT' => 'binance',
            'LSKUSDT' => 'binance',
            'WAVESUSDT' => 'binance',
            'BANDUSDT' => 'binance',
            'OCEANUSDT' => 'binance',
            'NMRUSDT' => 'binance',
            'NEARUSDT' => 'binance',
            'FTTUSDT' => 'binance',
            'ALICEUSDT' => 'binance',
            'CHZUSDT' => 'binance',
            'ENJUSDT' => 'binance',
            'MANAUSDT' => 'binance',
            'SANDUSDT' => 'binance',
            'GALAUSDT' => 'binance',
            'APEUSDT' => 'binance',
            'LOOKSUSDT' => 'binance',
            'IMXUSDT' => 'binance',
            'FLOWUSDT' => 'binance',
            'AXSUSDT' => 'binance',
            'DYDXUSDT' => 'binance',
            'GRTUSDT' => 'binance',
            'LPTUSDT' => 'binance',
            'API3USDT' => 'binance',
            'TLMUSDT' => 'binance',
            'PEOPLEUSDT' => 'binance',
            'ROSEUSDT' => 'binance',
            'SKLUSDT' => 'binance',
            'CELOUSDT' => 'binance',
            'KLAYUSDT' => 'binance',
            'SXPUSDT' => 'binance',
            'RUNEUSDT' => 'binance',
            'LINAUSDT' => 'binance',
            'MTLUSDT' => 'binance',
            'ZECUSDT' => 'binance',
            'DASHUSDT' => 'binance',
            'SCUSDT' => 'binance',
            'CHRUSDT' => 'binance',
            'XEMUSDT' => 'binance',
            'STORJUSDT' => 'binance',
            'BLZUSDT' => 'binance',
            'IRISUSDT' => 'binance',
            'COTIUSDT' => 'binance',
            'STPTUSDT' => 'binance',
            'DATAUSDT' => 'binance',
            'KEYUSDT' => 'binance',
            'DOCKUSDT' => 'binance',
            'WANUSDT' => 'binance',
            'FUNUSDT' => 'binance',
            'CVCUSDT' => 'binance',
            'VIAUSDT' => 'binance',
            'BEAMUSDT' => 'binance',
            'ARDRUSDT' => 'binance',
            'DGBUSDT' => 'binance',
            'STEEMUSDT' => 'binance',
            'STRATISUSDT' => 'binance',
            'ARKUSDT' => 'binance',
            'GRSUSDT' => 'binance',
            'VTCUSDT' => 'binance',
            'GAMEUSDT' => 'binance',
            'DCRUSDT' => 'binance',
            'PIVXUSDT' => 'binance',
            'XWCUSDT' => 'binance',
            'NXTUSDT' => 'binance',
            'BURGUSDT' => 'binance',
            'GBYTEUSDT' => 'binance',
            'NLGUSDT' => 'binance',
            'RBYUSDT' => 'binance',
            'POTUSDT' => 'binance',
            'BLKUSDT' => 'binance',
            'EMC2USDT' => 'binance',
            'RICUSDT' => 'binance',
            'FLOUSDT' => 'binance',
            'MAIDUSDT' => 'binance',
            'EXPUSDT' => 'binance',
            'GRCUSDT' => 'binance',
            'CLAMUSDT' => 'binance',
            'NVCUSDT' => 'binance',
            'CUREUSDT' => 'binance',
            'STARTUSDT' => 'binance',
            'XDNUSDT' => 'binance',
            'XSTUSDT' => 'binance',
            'BITBUSDT' => 'binance',
            'SIBUSDT' => 'binance',
            'SYSCUSDT' => 'binance',
            'NEOSUSDT' => 'binance',
            'XCPUSDT' => 'binance',
            'MONAUSDT' => 'binance',
            'CLUBUSDT' => 'binance',
            'VRCUSDT' => 'binance',
            'TIPSUSDT' => 'binance',
            'HIFUNUSDT' => 'binance',
            'ADCUSDT' => 'binance',
            'SLGUSDT' => 'binance',
            'CORGUSDT' => 'binance',
            'AIBUSDT' => 'binance',
            'GEOUSDT' => 'binance',
            'FLDCUSDT' => 'binance',
            'HYPUSDT' => 'binance',
            'HYPEUSDT' => 'binance',
            'ASTERUSDT' => 'binance',
            'XPLUSDT' => 'binance',
            'GOUSDT' => 'binance',
            'ERCUSDT' => 'binance',
            'VDOUSDT' => 'binance',
            'SXCUSDT' => 'binance',
            'LKYUSDT' => 'binance',
            'CPCUSDT' => 'binance',
            'NOTEUSDT' => 'binance',
            'EMDUSDT' => 'binance',
            'LYNXUSDT' => 'binance',
            'DBIXUSDT' => 'binance',
            'MEMEUSDT' => 'binance',
            'CSUSDT' => 'binance',
            'PHSUSDT' => 'binance',
            'NETUSDT' => 'binance',
            'BOSUSDT' => 'binance',
            'QWARKUSDT' => 'binance',
            'TERUSDT' => 'binance',
            'SWINGUSDT' => 'binance',
            'SAKUSDT' => 'binance',
            '32BITUSDT' => 'binance',
            'COVALUSDT' => 'binance',
            'EDGUSDT' => 'binance',
            'HEATUSDT' => 'binance',
            'CLOAKUSDT' => 'binance',
            'XELUSDT' => 'binance',
            'AMPUSDT' => 'binance',
            'DMDUSDT' => 'binance',
            'GAMUSDT' => 'binance',
            'SPHRUSDT' => 'binance',
            'NXSUSDT' => 'binance',
        ],

        // Fallback APIs for coins (if primary fails)
        'fallback_apis' => [
            'BTCUSDT' => ['binance', 'coincappro', 'coingecko', 'freecryptoapi', 'coinlore'],
            'ETHUSDT' => ['binance', 'coincappro', 'coingecko', 'freecryptoapi', 'coinlore'],
            'BNBUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ADAUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'XRPUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'SOLUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'DOTUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'DOGEUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'AVAXUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'LTCUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'LINKUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'MATICUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ALGOUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'UNIUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ATOMUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'VETUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ICPUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'FILUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'TRXUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ETCUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
        ],

        // API-specific coin limitations
        'api_limitations' => [
            'binance' => [
                'max_klines_limit' => 1000,
                'supported_intervals' => ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M'],
                'requires_uppercase' => true,
                'supported_quote_assets' => ['USDT', 'BTC', 'ETH', 'BUSD'],
            ],
            'coingecko' => [
                'max_klines_limit' => 365,
                'supported_intervals' => ['1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'coin_id_mapping' => [
                    'BTCUSDT' => 'bitcoin',
                    'ETHUSDT' => 'ethereum',
                    'BNBUSDT' => 'binancecoin',
                    'ADAUSDT' => 'cardano',
                    'XRPUSDT' => 'ripple',
                    'SOLUSDT' => 'solana',
                    'DOTUSDT' => 'polkadot',
                    'DOGEUSDT' => 'dogecoin',
                    'AVAXUSDT' => 'avalanche-2',
                    'LTCUSDT' => 'litecoin',
                    'LINKUSDT' => 'chainlink',
                    'MATICUSDT' => 'matic-network',
                    'ALGOUSDT' => 'algorand',
                    'UNIUSDT' => 'uniswap',
                    'ATOMUSDT' => 'cosmos',
                    'VETUSDT' => 'vechain',
                    'ICPUSDT' => 'internet-computer',
                    'FILUSDT' => 'filecoin',
                    'TRXUSDT' => 'tron',
                    'ETCUSDT' => 'ethereum-classic',
                ],
            ],
            'freecryptoapi' => [
                'max_klines_limit' => 500,
                'supported_intervals' => ['1m', '5m', '15m', '30m', '1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'symbol_format' => 'BTC-USDT', // Different format
                'coin_id_mapping' => [
                    'BTCUSDT' => 'BTC-USDT',
                    'ETHUSDT' => 'ETH-USDT',
                    'BNBUSDT' => 'BNB-USDT',
                    'ADAUSDT' => 'ADA-USDT',
                    'XRPUSDT' => 'XRP-USDT',
                    'SOLUSDT' => 'SOL-USDT',
                    'DOTUSDT' => 'DOT-USDT',
                    'DOGEUSDT' => 'DOGE-USDT',
                    'AVAXUSDT' => 'AVAX-USDT',
                    'LTCUSDT' => 'LTC-USDT',
                    'LINKUSDT' => 'LINK-USDT',
                    'MATICUSDT' => 'MATIC-USDT',
                    'ALGOUSDT' => 'ALGO-USDT',
                    'UNIUSDT' => 'UNI-USDT',
                    'ATOMUSDT' => 'ATOM-USDT',
                    'VETUSDT' => 'VET-USDT',
                    'ICPUSDT' => 'ICP-USDT',
                    'FILUSDT' => 'FIL-USDT',
                    'TRXUSDT' => 'TRX-USDT',
                    'ETCUSDT' => 'ETC-USDT',
                ],
            ],
        ],
    ],
];