<?php

// config/crypto.php
return [
    // Currency Configuration
    'currencies' => [
        'primary' => 'USD',
        'secondary' => 'IDR',
    ],

    // Exchange Rates
    'usd_to_idr' => env('USD_TO_IDR', 16500),

    // Currency API Configuration
    'currency_api' => [
        'url' => env('CURRENCY_API_URL', 'https://api.exchangerate-api.com/v4/latest/USD'),
        'key' => env('CURRENCY_API_KEY', ''), // Optional API key for premium features
        'enabled' => env('CURRENCY_API_ENABLED', true),
        'cache_duration' => env('CURRENCY_CACHE_DURATION', 21600), // 6 hours in seconds
    ],

    // Currency Display Settings
    'currency_display' => [
        'show_both_currencies' => env('SHOW_BOTH_CURRENCIES', true),
        'usd_decimals' => env('USD_DECIMALS', 2),
        'idr_decimals' => env('IDR_DECIMALS', 0),
        'format_style' => env('CURRENCY_FORMAT_STYLE', 'USD_IDR'), // USD_IDR, IDR_USD, USD_ONLY, IDR_ONLY
        'always_show_both' => true, // Always show both USD and IDR regardless of format_style
    ],

    // Definisikan timeframe yang akan dianalisis
    'timeframes' => [
        '1h' => ['label' => 'H1', 'limit' => 300],
        '4h' => ['label' => 'H4', 'limit' => 300],
        '1d' => ['label' => '1D', 'limit' => 300],
    ],

    // Tentukan timeframe mana yang menjadi acuan utama dan konfirmasi
    'main_timeframe_label' => 'H4',
    'confirmation_timeframe_label' => 'H1',

    // Parameter untuk indikator teknikal
    'indicators' => [
        'ema_short' => 9,
        'ema_long' => 21,
        'ema_trend' => 200,
        'rsi_period' => 14,
        'macd_fast' => 12,
        'macd_slow' => 26,
        'macd_signal' => 9,
    ],

    // Pembobotan skor untuk setiap indikator
    'scoring_weights' => [
        'trend' => 3.0,     // EMA 200 Trend
        'momentum' => 1.5,  // EMA 9 vs 21
        'macd' => 2.0,
        'rsi' => 1.0,
        'volume' => 1.5,    // Indikator baru: Volume
    ],

    // Aturan untuk pengambilan keputusan final
    'decision_rules' => [
        'main_tf_buy_threshold' => 2.0,
        'confirm_tf_buy_threshold' => 1.0,
        'main_tf_sell_threshold' => -2.0,
        'confirm_tf_sell_threshold' => -1.0,
    ],

    // Binance API Configuration
    'binance_api' => [
        'base_url' => env('BINANCE_API_URL', 'https://api.binance.com'),
        'exchange_info_endpoint' => '/api/v3/exchangeInfo',
        'ticker_endpoint' => '/api/v3/ticker/price',
        'klines_endpoint' => '/api/v3/klines',
        'timeout' => env('BINANCE_API_TIMEOUT', 30),
        'retry_attempts' => env('BINANCE_API_RETRY', 3),
        'retry_delay' => env('BINANCE_API_RETRY_DELAY', 1000), // milliseconds
    ],

    // Symbol filtering options
    'symbol_filters' => [
        'quote_assets' => ['USDT', 'BTC', 'ETH', 'BUSD'], // Only include these quote assets
        'exclude_symbols' => ['UP', 'DOWN', 'BULL', 'BEAR'], // Exclude leveraged tokens
        'min_volume_24h' => env('MIN_24H_VOLUME', 100000), // Minimum 24h volume in USD
        'max_symbols' => env('MAX_SYMBOLS', 500), // Limit number of symbols to fetch
    ],

    // API Provider Configuration
    'api_providers' => [
        'default' => env('DEFAULT_API_PROVIDER', 'binance'),
        'fallback_enabled' => env('API_FALLBACK_ENABLED', true),
        'rate_limit_cache_duration' => env('API_RATE_LIMIT_CACHE', 300), // 5 minutes
        'providers' => [
            'binance' => [
                'name' => 'Binance API',
                'priority' => 0, // Highest priority
                'enabled' => env('BINANCE_API_ENABLED', true),
                'base_url' => env('BINANCE_API_URL', 'https://api.binance.com'),
                'timeout' => env('BINANCE_API_TIMEOUT', 30),
                'retry_attempts' => env('BINANCE_API_RETRY', 3),
                'retry_delay' => env('BINANCE_API_RETRY_DELAY', 1000),
                'rate_limits' => [
                    'requests_per_minute' => env('BINANCE_RATE_LIMIT', 1200),
                    'requests_per_second' => env('BINANCE_RATE_LIMIT_SECOND', 10),
                ],
            ],
            'coingecko' => [
                'name' => 'CoinGecko API',
                'priority' => 1, // Second priority
                'enabled' => env('COINGECKO_API_ENABLED', true),
                'base_url' => env('COINGECKO_API_URL', 'https://api.coingecko.com/api/v3'),
                'api_key' => env('COINGECKO_API_KEY', ''),
                'timeout' => env('COINGECKO_API_TIMEOUT', 30),
                'retry_attempts' => env('COINGECKO_API_RETRY', 3),
                'retry_delay' => env('COINGECKO_API_RETRY_DELAY', 2000),
                'rate_limits' => [
                    'requests_per_minute' => env('COINGECKO_RATE_LIMIT', 50),
                    'requests_per_second' => env('COINGECKO_RATE_LIMIT_SECOND', 2),
                ],
            ],
            'freecryptoapi' => [
                'name' => 'Free Crypto API',
                'priority' => 2, // Third priority (fallback)
                'enabled' => env('FREECRYPTOAPI_ENABLED', true),
                'base_url' => env('FREECRYPTOAPI_URL', 'https://freecryptoapi.com/api/v1'),
                'api_key' => env('FREECRYPTOAPI_KEY', 'xccc177q0n8g9cf3t43n'),
                'timeout' => env('FREECRYPTOAPI_TIMEOUT', 30),
                'retry_attempts' => env('FREECRYPTOAPI_RETRY', 3),
                'retry_delay' => env('FREECRYPTOAPI_RETRY_DELAY', 3000),
                'rate_limits' => [
                    'requests_per_minute' => env('FREECRYPTOAPI_RATE_LIMIT', 100),
                    'requests_per_second' => env('FREECRYPTOAPI_RATE_LIMIT_SECOND', 2),
                ],
            ],
        ],
    ],

    // Coin-to-API Mapping Configuration
    'coin_api_mapping' => [
        // Primary API for each coin (first priority)
        'primary_api' => [
            // Binance USDT pairs (most comprehensive)
            'BTCUSDT' => 'binance',
            'ETHUSDT' => 'binance',
            'BNBUSDT' => 'binance',
            'ADAUSDT' => 'binance',
            'XRPUSDT' => 'binance',
            'SOLUSDT' => 'binance',
            'DOTUSDT' => 'binance',
            'DOGEUSDT' => 'binance',
            'AVAXUSDT' => 'binance',
            'LTCUSDT' => 'binance',
            'LINKUSDT' => 'binance',
            'MATICUSDT' => 'binance',
            'ALGOUSDT' => 'binance',
            'UNIUSDT' => 'binance',
            'ATOMUSDT' => 'binance',
            'VETUSDT' => 'binance',
            'ICPUSDT' => 'binance',
            'FILUSDT' => 'binance',
            'TRXUSDT' => 'binance',
            'ETCUSDT' => 'binance',
            'XLMUSDT' => 'binance',
            'THETAUSDT' => 'binance',
            'EOSUSDT' => 'binance',
            'AAVEUSDT' => 'binance',
            'COMPUSDT' => 'binance',
            'SNXUSDT' => 'binance',
            'YFIUSDT' => 'binance',
            'SUSHIUSDT' => 'binance',
            'CRVUSDT' => 'binance',
            'MKRUSDT' => 'binance',
            'UMAUSDT' => 'binance',
            'ZRXUSDT' => 'binance',
            'BATUSDT' => 'binance',
            'ZILUSDT' => 'binance',
            'ONTUSDT' => 'binance',
            'QTUMUSDT' => 'binance',
            'ICXUSDT' => 'binance',
            'LSKUSDT' => 'binance',
            'WAVESUSDT' => 'binance',
            'BANDUSDT' => 'binance',
            'OCEANUSDT' => 'binance',
            'NMRUSDT' => 'binance',
            'NEARUSDT' => 'binance',
            'FTTUSDT' => 'binance',
            'ALICEUSDT' => 'binance',
            'CHZUSDT' => 'binance',
            'ENJUSDT' => 'binance',
            'MANAUSDT' => 'binance',
            'SANDUSDT' => 'binance',
            'GALAUSDT' => 'binance',
            'APEUSDT' => 'binance',
            'LOOKSUSDT' => 'binance',
            'IMXUSDT' => 'binance',
            'FLOWUSDT' => 'binance',
            'AXSUSDT' => 'binance',
            'DYDXUSDT' => 'binance',
            'GRTUSDT' => 'binance',
            'LPTUSDT' => 'binance',
            'API3USDT' => 'binance',
            'TLMUSDT' => 'binance',
            'PEOPLEUSDT' => 'binance',
            'ROSEUSDT' => 'binance',
            'SKLUSDT' => 'binance',
            'CELOUSDT' => 'binance',
            'KLAYUSDT' => 'binance',
            'SXPUSDT' => 'binance',
            'RUNEUSDT' => 'binance',
            'LINAUSDT' => 'binance',
            'MTLUSDT' => 'binance',
            'ZECUSDT' => 'binance',
            'DASHUSDT' => 'binance',
            'SCUSDT' => 'binance',
            'CHRUSDT' => 'binance',
            'XEMUSDT' => 'binance',
            'STORJUSDT' => 'binance',
            'BLZUSDT' => 'binance',
            'IRISUSDT' => 'binance',
            'COTIUSDT' => 'binance',
            'STPTUSDT' => 'binance',
            'DATAUSDT' => 'binance',
            'KEYUSDT' => 'binance',
            'DOCKUSDT' => 'binance',
            'WANUSDT' => 'binance',
            'FUNUSDT' => 'binance',
            'CVCUSDT' => 'binance',
            'VIAUSDT' => 'binance',
            'BEAMUSDT' => 'binance',
            'ARDRUSDT' => 'binance',
            'DGBUSDT' => 'binance',
            'STEEMUSDT' => 'binance',
            'STRATISUSDT' => 'binance',
            'ARKUSDT' => 'binance',
            'GRSUSDT' => 'binance',
            'VTCUSDT' => 'binance',
            'GAMEUSDT' => 'binance',
            'DCRUSDT' => 'binance',
            'PIVXUSDT' => 'binance',
            'XWCUSDT' => 'binance',
            'NXTUSDT' => 'binance',
            'BURGUSDT' => 'binance',
            'GBYTEUSDT' => 'binance',
            'NLGUSDT' => 'binance',
            'RBYUSDT' => 'binance',
            'POTUSDT' => 'binance',
            'BLKUSDT' => 'binance',
            'EMC2USDT' => 'binance',
            'RICUSDT' => 'binance',
            'FLOUSDT' => 'binance',
            'MAIDUSDT' => 'binance',
            'EXPUSDT' => 'binance',
            'GRCUSDT' => 'binance',
            'CLAMUSDT' => 'binance',
            'NVCUSDT' => 'binance',
            'CUREUSDT' => 'binance',
            'STARTUSDT' => 'binance',
            'XDNUSDT' => 'binance',
            'XSTUSDT' => 'binance',
            'BITBUSDT' => 'binance',
            'SIBUSDT' => 'binance',
            'SYSCUSDT' => 'binance',
            'NEOSUSDT' => 'binance',
            'XCPUSDT' => 'binance',
            'MONAUSDT' => 'binance',
            'CLUBUSDT' => 'binance',
            'VRCUSDT' => 'binance',
            'TIPSUSDT' => 'binance',
            'HIFUNUSDT' => 'binance',
            'ADCUSDT' => 'binance',
            'SLGUSDT' => 'binance',
            'CORGUSDT' => 'binance',
            'AIBUSDT' => 'binance',
            'GEOUSDT' => 'binance',
            'FLDCUSDT' => 'binance',
            'HYPUSDT' => 'binance',
            'GOUSDT' => 'binance',
            'ERCUSDT' => 'binance',
            'VDOUSDT' => 'binance',
            'SXCUSDT' => 'binance',
            'LKYUSDT' => 'binance',
            'CPCUSDT' => 'binance',
            'NOTEUSDT' => 'binance',
            'EMDUSDT' => 'binance',
            'LYNXUSDT' => 'binance',
            'DBIXUSDT' => 'binance',
            'MEMEUSDT' => 'binance',
            'CSUSDT' => 'binance',
            'PHSUSDT' => 'binance',
            'NETUSDT' => 'binance',
            'BOSUSDT' => 'binance',
            'QWARKUSDT' => 'binance',
            'TERUSDT' => 'binance',
            'SWINGUSDT' => 'binance',
            'SAKUSDT' => 'binance',
            '32BITUSDT' => 'binance',
            'COVALUSDT' => 'binance',
            'EDGUSDT' => 'binance',
            'HEATUSDT' => 'binance',
            'CLOAKUSDT' => 'binance',
            'XELUSDT' => 'binance',
            'AMPUSDT' => 'binance',
            'DMDUSDT' => 'binance',
            'GAMUSDT' => 'binance',
            'SPHRUSDT' => 'binance',
            'NXSUSDT' => 'binance',
        ],

        // Fallback APIs for coins (if primary fails)
        'fallback_apis' => [
            'BTCUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ETHUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'BNBUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ADAUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'XRPUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'SOLUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'DOTUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'DOGEUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'AVAXUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'LTCUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'LINKUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'MATICUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ALGOUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'UNIUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ATOMUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'VETUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ICPUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'FILUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'TRXUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
            'ETCUSDT' => ['binance', 'coingecko', 'freecryptoapi'],
        ],

        // API-specific coin limitations
        'api_limitations' => [
            'binance' => [
                'max_klines_limit' => 1000,
                'supported_intervals' => ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M'],
                'requires_uppercase' => true,
                'supported_quote_assets' => ['USDT', 'BTC', 'ETH', 'BUSD'],
            ],
            'coingecko' => [
                'max_klines_limit' => 365,
                'supported_intervals' => ['1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'coin_id_mapping' => [
                    'BTCUSDT' => 'bitcoin',
                    'ETHUSDT' => 'ethereum',
                    'BNBUSDT' => 'binancecoin',
                    'ADAUSDT' => 'cardano',
                    'XRPUSDT' => 'ripple',
                    'SOLUSDT' => 'solana',
                    'DOTUSDT' => 'polkadot',
                    'DOGEUSDT' => 'dogecoin',
                    'AVAXUSDT' => 'avalanche-2',
                    'LTCUSDT' => 'litecoin',
                    'LINKUSDT' => 'chainlink',
                    'MATICUSDT' => 'matic-network',
                    'ALGOUSDT' => 'algorand',
                    'UNIUSDT' => 'uniswap',
                    'ATOMUSDT' => 'cosmos',
                    'VETUSDT' => 'vechain',
                    'ICPUSDT' => 'internet-computer',
                    'FILUSDT' => 'filecoin',
                    'TRXUSDT' => 'tron',
                    'ETCUSDT' => 'ethereum-classic',
                ],
            ],
            'freecryptoapi' => [
                'max_klines_limit' => 500,
                'supported_intervals' => ['1m', '5m', '15m', '30m', '1h', '4h', '1d'],
                'requires_uppercase' => false,
                'supported_quote_assets' => ['usd'],
                'symbol_format' => 'BTC-USDT', // Different format
                'coin_id_mapping' => [
                    'BTCUSDT' => 'BTC-USDT',
                    'ETHUSDT' => 'ETH-USDT',
                    'BNBUSDT' => 'BNB-USDT',
                    'ADAUSDT' => 'ADA-USDT',
                    'XRPUSDT' => 'XRP-USDT',
                    'SOLUSDT' => 'SOL-USDT',
                    'DOTUSDT' => 'DOT-USDT',
                    'DOGEUSDT' => 'DOGE-USDT',
                    'AVAXUSDT' => 'AVAX-USDT',
                    'LTCUSDT' => 'LTC-USDT',
                    'LINKUSDT' => 'LINK-USDT',
                    'MATICUSDT' => 'MATIC-USDT',
                    'ALGOUSDT' => 'ALGO-USDT',
                    'UNIUSDT' => 'UNI-USDT',
                    'ATOMUSDT' => 'ATOM-USDT',
                    'VETUSDT' => 'VET-USDT',
                    'ICPUSDT' => 'ICP-USDT',
                    'FILUSDT' => 'FIL-USDT',
                    'TRXUSDT' => 'TRX-USDT',
                    'ETCUSDT' => 'ETC-USDT',
                ],
            ],
        ],
    ],
];